//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
/// </summary>
// StronglyTypedResourceBuilder generó automáticamente esta clase
// a través de una herramienta como ResGen o Visual Studio.
// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
// con la opción /str o recompile su proyecto de VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class ns1_Class1 {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ns1_Class1() {
    }
    
    /// <summary>
    ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ns1.Class1", typeof(ns1_Class1).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap iphone6 {
        get {
            object obj = ResourceManager.GetObject("iphone6", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap iphone7_8 {
        get {
            object obj = ResourceManager.GetObject("iphone7/8", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap iphoneX {
        get {
            object obj = ResourceManager.GetObject("iphoneX", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Busca un recurso adaptado de tipo System.Byte[].
    /// </summary>
    internal static byte[] resx {
        get {
            object obj = ResourceManager.GetObject("resx", resourceCulture);
            return ((byte[])(obj));
        }
    }
}
